# Generated by Django 5.1.3 on 2024-12-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffe',
            old_name='conent',
            new_name='content',
        ),
    ]
